repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace    # Убирает лишние пробелы
      - id: end-of-file-fixer      # Проверяет, чтобы в конце файла была пустая строка

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [--max-line-length=88]

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black                  # Автоматическое форматирование кода
